import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="navigation">
    {/* //   <h1>Homepage</h1>
    //   <p className="headline">
    //     This project was generated By{" "}
    //     <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
    //     to navigate through all pages.
    //   </p> */}
      <ul>
        <li>
          <Link to="/homeone">HomeOne</Link>
        </li>
        <li>
          <Link to="/aboutus">Aboutus</Link>
        </li>
        <li>
          <Link to="/ourservices">OurServices</Link>
        </li>
        <li>
          <Link to="/appdevelopment">AppDevelopment</Link>
        </li>
        <li>
          <Link to="/webdevelopment">WebDevelopment</Link>
        </li>
        <li>
          <Link to="/contactus">ContactUs</Link>
        </li>
        <li>
          <Link to="/joinus">Joinus</Link>
        </li>
        <li>
          <Link to="/wordpressdeveloper">WordPressDeveloper</Link>
        </li>
        <li>
          <Link to="/jobapplicationformone">JobapplicationformOne</Link>
        </li>
        <li>
          <Link to="/jobapplicationform">Jobapplicationform</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
